### ISSUE TITLE
AttributeError: 'TclError' object has no attribute 'message'

### ISSUE THREAD

**Issue by littlewhitecloud** [tomlin7/biscuit#84] opened 2023-07-18 10:54 UTC
## Bug
> Describe the bug

I do `python biscuit` and it shows me that:
```
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\site-packages\tkextrafont\__init__.py", line 118, in load
    window.tk.eval("package require extrafont")
_tkinter.TclError: extra characters after close-brace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\__main__.py", line 15, in <module>
    app = App(dir=dir)
          ^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\app.py", line 36, in __init__
    self.setup()
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\app.py", line 48, in setup
    self.setup_configs()
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\app.py", line 93, in setup_configs
    self.settings = Settings(self)
                    ^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\core\settings\__init__.py", line 31, in __init__
    self.setup_properties()
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\core\settings\__init__.py", line 64, in setup_properties
    self.setup_font()
  File "C:\Users\Administrator\Downloads\Biscuit-main\Biscuit-main\biscuit\core\settings\__init__.py", line 76, in setup_font
    self.firacodefont = extra.Font(file=os.path.join(self.base.resdir, "fonts/firacode/firacode.ttf"), family="firacode")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\tkextrafont\__init__.py", line 90, in __init__
    load(root)
  File "C:\Program Files\Python311\Lib\site-packages\tkextrafont\__init__.py", line 120, in load
    if "libfontconfig" in e.message:
                          ^^^^^^^^^
AttributeError: 'TclError' object has no attribute 'message'
```

### System Information
- OS: Windows
- Python Version: 3.11.4

**Comment by billyeatcookies** [comment] 2023-07-18 13:17
@littlewhitecloud Thank you for reporting this error! ❤ While I thought this was caused due to Python version `3.11.4` (maybe due to tcl updates, I was running `3.11.3`), I tried to update Python and check again, but I was unable to reproduce the error. I will look into it, and test it in a few more machines!

**Comment by littlewhitecloud** [comment] 2023-07-18 22:28
> @littlewhitecloud Thank you for reporting this error! ❤ While I thought this was caused due to Python version `3.11.4` (maybe due to tcl updates, I was running `3.11.3`), I tried to update Python and check again, but I was unable to reproduce the error. I will look into it, and test it in a few more machines!

Thank you for checking out this! I will try to use python 3.10 to run biscuit. I remember that there is error.message syntax.

**Comment by littlewhitecloud** [comment] 2023-07-19 00:57
![image](https://github.com/billyeatcookies/Biscuit/assets/71159641/c16ca501-fbd9-4a66-a7ad-99179d1503e6)
Also on Python 3.10.1

**Comment by littlewhitecloud** [comment] 2023-07-19 07:14
@billyeatcookies can you tell me which python version are you using?

**Comment by billyeatcookies** [comment] 2023-07-19 11:29
@littlewhitecloud I have been looking into reproducing the errors you are getting, but still couldn't. I have tested on both **3.11.3** and **3.11.4** without getting any errors. 

https://github.com/billyeatcookies/Biscuit/assets/70792552/a5dfc046-4a88-4605-b48a-a33fc7bc7efa

(my recorder is having some issues, the editor is much more smooth that shown)

**Comment by littlewhitecloud** [comment] 2023-07-19 12:07
Again on my another computer...
@billyeatcookies can you show me your tkextrafont's __init__.py?

**Comment by billyeatcookies** [comment] 2023-07-19 19:50
@littlewhitecloud no changes were made to the libs used, they are used as they are. this one specific lib that is throwing an error here is `tkextrafont`. I will let you know of any updates!

**Comment by billyeatcookies** [comment] 2023-07-27 19:11
@littlewhitecloud seems the issue has been fixed, receiving some info from @rdbende, I can say that this is more of an issue with the font, some are not supported. I have removed the unnecessary fonts, let me know if you test again!

**Comment by rdbende** [comment] 2023-07-27 21:03
Wait, @billyeatcookies. That was the other issue, this one happens during installation. The `KeyError` is the one that happens with unsupported fonts :))

**Comment by littlewhitecloud** [comment] 2023-07-28 00:11
> @littlewhitecloud seems the issue has been fixed, receiving some info from @rdbende, I can say that this is more of an issue with the font, some are not supported. I have removed the unnecessary fonts, let me know if you test again!

Thank you very much! I will take time test it!

**Comment by billyeatcookies** [comment] 2023-07-28 11:16
@rdbende oh yess my bad! it was
```
    self.firacodefont = extra.Font(file=os.path.join(self.base.resdir, "fonts/firacode/firacode.ttf"), family="firacode")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cid0rz/.pyenv/versions/test311/lib/python3.11/site-packages/tkextrafont/__init__.py", line 92, in __init__
    root.tk.call("extrafont::load", file)
_tkinter.TclError: key "fontFamily" not known in dictionary
```

but if this one was caused by the specific font, it shall be fixed by now i hope

**Comment by littlewhitecloud** [comment] 2023-07-28 11:39
Thanks! I tested it on my new computer and it looks well!
![image](https://github.com/billyeatcookies/Biscuit/assets/71159641/133dab2a-4bf3-4a69-a4b7-4302794edea6)

BTW, I noticed that the window has a custom titlebar and it looks great!
But the window's border looks laggy.
@billyeatcookies Maybe you can check out my laggy repo: CustomTkinterTitlebar, even it isn't very good.

**Comment by littlewhitecloud** [comment] 2023-07-28 11:45
But there is something wrong with the windows border, it has 6px white frame (just the frame above the "titlebar" with mica effect in the picture) I hate that and I am tring to get rid off it (Really hard)
[I don't know why Microsoft add the 6px white frame in the windows10 and version above]

**Comment by billyeatcookies** [comment] 2023-07-28 16:04
@littlewhitecloud thanks for testing out! the current titlebar works notso fine and i had to reconfigure all window manager features manually when i did it, would check CustomTkinterTitlebar at a point and see if it can manage this better!

about the border, the only reason it was added was for the resizing feature of window, which was lost after `overrideredict` flag.  Maybe can add a toggle option for the color in settings later!

also comments on the CustomTkinterTitlebar, I cant say much about the padding issue there since I have not worked with win32 API. Seems the solution is pretty windows specific, it should be cross-platform at a point, so focus on that too :)

**Closed as completed** 2023-07-28 16:05 UTC
Labels: bug, python-error

**Comment by rdbende** [comment] 2023-07-28 17:02
btw, @billyeatcookies, this custom titlebar thingy doesn't really work well on Linux (at least on my system: Wayland + GNOME (uses the Mutter window manager)). Because of `.wm_overrideredirect()` it stays always on top, and the filedialog goes behind the window. Resizing doesn't work, and any of the menus either. The menus open, but as soon as I move the mouse, they disappear, and selecting items with the keyboard doesn't work either :((

**Comment by billyeatcookies** [comment] 2023-07-28 17:58
@rdbende thanks for letting me know ❤ Does setting `-topmost` flag stop this always-on-top behavior of windows after `.wm_overrideredirect()`? have you tried `.wm_overrideredirect()` on any projects before, if so how did they behave and have you found any fixes for them?

**Comment by rdbende** [comment] 2023-07-28 19:04
> Does setting `-topmost` flag stop this always-on-top behavior of windows after `.wm_overrideredirect()`?

It doesn't. I think it's because when you call `.wm_overrideredirect(True)` it tells the window manager, to disregard that window, and therefore the window will have no idea about the stacking order.

> have you tried `.wm_overrideredirect()` on any projects before, if so how did they behave and have you found any fixes for them?

No, but judging from my conclusion above, it is probably not possible :((

**Comment by rdbende** [comment] 2023-07-28 19:19
> Resizing doesn't work, and any of the menus either. 

No idea what happened, resizing works now, and the menus doesn't close immediately. However, they now can't be dismissed at all, and the items can't be activated.

**Comment by littlewhitecloud** [comment] 2023-07-28 23:20
Actually CustomTkinterTitlebar only works for windows(I can’t test on any other platform)
